spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:h2:file:./data/database
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
#  sql:
#    init:
#      data-locations: classpath:/data/data.sql
#      mode: always